language: objective-c
osx_image: xcode9.2
branches:
  - master
cache:
  - bundler
env:
  matrix:
    - FASTLANE_ENV=iOS
    - FASTLANE_ENV=macOS
script:
  - bundle exec fastlane test --env $FASTLANE_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
