language: objective-c
osx_image: xcode9.2
branches:
  - master
cache:
  - bundler
env:
  matrix:
    - FASTLANE_ENV=iOS
    - FASTLANE_ENV=macOS
script:
  - bundle exec fastlane test --env $FASTLANE_ENV
before_deploy:
  - carthage build --no-skip-current
  - carthage archive
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    file: HCImageBPG.framework.zip
    skip_cleanup: true
    on:
      tags: true
      repo: chuganzy/HCImage-BPG
  - provider: script
    script: bundle exec pod trunk push
    on:
      tags: true
      repo: chuganzy/HCImage-BPG
