os: osx
osx_image: xcode7.1
env:
  matrix:
    - PLATFORM=iOS
    - PLATFORM=Mac
script:
- set -o pipefail
- cd Example/"$PLATFORM"
- pod install
- xcodebuild -workspace Example.xcworkspace -scheme Example
